import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Octokit } from '@octokit/rest';
import { SummaryResult } from '../llm/llm.interface';

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);
  private readonly octokit: Octokit;
  private readonly owner: string;
  private readonly repo: string;
  private readonly summaryDir: string;

  constructor(private readonly configService: ConfigService) {
    const token = this.configService.get<string>('github.token');
    const repoFullName = this.configService.get<string>('github.repo');

    const [owner, repo] = repoFullName.split('/');
    this.owner = owner;
    this.repo = repo;

    this.summaryDir = this.configService.get<string>('github.summaryDir');
    this.octokit = new Octokit({ auth: token });
  }

  async saveMarkdown(
    result: SummaryResult,
    sourceUrl: string,
  ): Promise<string> {
    const today = this.getToday();
    const path = `${this.summaryDir}/${today}-${result.description}.md`;
    const content = this.buildMarkdown(result, sourceUrl, today);
    const message = `docs: add summary - ${result.title}`;

    this.logger.log(`Saving markdown to ${path}`);

    const response = await this.octokit.repos.createOrUpdateFileContents({
      owner: this.owner,
      repo: this.repo,
      path,
      message,
      content: Buffer.from(content).toString('base64'),
    });

    const htmlUrl = response.data.content?.html_url ?? '';
    this.logger.log(`Markdown saved: ${htmlUrl}`);

    return htmlUrl;
  }

  private buildMarkdown(
    result: SummaryResult,
    sourceUrl: string,
    date: string,
  ): string {
    const tagsStr = result.tags.map((t) => `${t}`).join(', ');
    const keywordsStr = result.keywords.join(', ');

    const lines = [
      '---',
      `title: "${result.title}"`,
      `date: ${date}`,
      `category: ${result.category}`,
      `tags: [${tagsStr}]`,
      `keywords: [${keywordsStr}]`,
      `source: "${sourceUrl}"`,
      '---',
      '',
    ];

    if (sourceUrl) {
      lines.push(`> 원문: ${sourceUrl}`, '');
    }

    // 한줄 요약
    lines.push('## 한줄 요약', '', result.oneline, '');

    // 핵심 인사이트
    lines.push('## 핵심 인사이트', '');
    for (const insight of result.insights) {
      const text =
        typeof insight === 'string' ? insight : JSON.stringify(insight);
      lines.push(`- ${text}`);
    }
    lines.push('');

    // 쉬운 해석
    lines.push('## 쉬운 해석', '', result.decoded, '');

    // 주요 원문
    lines.push('## 주요 원문', '');
    for (const quote of result.quotes) {
      lines.push(`> "${quote.text}"`, '', quote.context, '');
    }

    // 구분선
    lines.push('---', '');

    // 본문
    lines.push(result.summary, '');

    // 키워드
    lines.push(
      '## 키워드',
      '',
      result.keywords.map((k) => `\`${k}\``).join(' '),
      '',
    );

    // 지식 맵
    lines.push(
      '## 지식 맵',
      '',
      `- **상위**: ${result.concepts.upper.join(', ')}`,
      `- **하위**: ${result.concepts.lower.join(', ')}`,
      `- **연관**: ${result.concepts.related.join(', ')}`,
      `- **선행**: ${result.concepts.prerequisite.join(', ')}`,
      `- **후속**: ${result.concepts.followup.join(', ')}`,
      '',
      `> Auto-generated by Summary Bot on ${date}`,
      '',
    );

    return lines.join('\n');
  }

  private getToday(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }
}
