import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Octokit } from '@octokit/rest';
import { SummaryResult } from '../llm/llm.interface';

@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);
  private readonly octokit: Octokit;
  private readonly owner: string;
  private readonly repo: string;

  constructor(private readonly configService: ConfigService) {
    const token = this.configService.get<string>('github.token');
    const repoFullName = this.configService.get<string>('github.repo');

    const [owner, repo] = repoFullName.split('/');
    this.owner = owner;
    this.repo = repo;

    this.octokit = new Octokit({ auth: token });
  }

  async saveMarkdown(
    result: SummaryResult,
    sourceUrl: string,
  ): Promise<string> {
    const today = this.getToday();
    const path = `90-summaries/${today}-${result.description}.md`;
    const content = this.buildMarkdown(result, sourceUrl, today);
    const message = `docs: add summary - ${result.title}`;

    this.logger.log(`Saving markdown to ${path}`);

    const response = await this.octokit.repos.createOrUpdateFileContents({
      owner: this.owner,
      repo: this.repo,
      path,
      message,
      content: Buffer.from(content).toString('base64'),
    });

    const htmlUrl = response.data.content?.html_url ?? '';
    this.logger.log(`Markdown saved: ${htmlUrl}`);

    return htmlUrl;
  }

  private buildMarkdown(
    result: SummaryResult,
    sourceUrl: string,
    date: string,
  ): string {
    const tagsStr = result.tags.map((t) => `${t}`).join(', ');

    return [
      '---',
      `title: "${result.title}"`,
      `date: ${date}`,
      `category: ${result.category}`,
      `tags: [${tagsStr}]`,
      `source: "${sourceUrl}"`,
      '---',
      '',
      result.summary,
      '',
      `> Auto-generated by Summary Bot on ${date}`,
      '',
    ].join('\n');
  }

  private getToday(): string {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  }
}
