import { Test, TestingModule } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';
import { GithubService } from './github.service';

jest.mock('@octokit/rest', () => ({
  Octokit: jest.fn().mockImplementation(() => ({
    repos: {
      createOrUpdateFileContents: jest.fn().mockResolvedValue({
        data: {
          content: {
            html_url: 'https://github.com/owner/repo/blob/main/98-summaries/2026-02-10-test-slug.md',
          },
        },
      }),
      getContent: jest.fn().mockResolvedValue({
        data: { sha: 'abc123sha' },
      }),
      deleteFile: jest.fn().mockResolvedValue({}),
    },
  })),
}));

import { Octokit } from '@octokit/rest';

describe('GithubService', () => {
  let service: GithubService;
  let mockOctokit: jest.Mocked<any>;

  const mockConfigService = {
    get: jest.fn((key: string) => {
      const config = {
        'github.token': 'test-token',
        'github.repo': 'owner/repo',
        'github.summaryDir': '98-summaries',
      };
      return config[key];
    }),
  };

  beforeEach(async () => {
    jest.clearAllMocks();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        GithubService,
        { provide: ConfigService, useValue: mockConfigService },
      ],
    }).compile();

    service = module.get<GithubService>(GithubService);
    mockOctokit = (Octokit as jest.MockedClass<typeof Octokit>).mock.results[
      (Octokit as jest.MockedClass<typeof Octokit>).mock.results.length - 1
    ].value;
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  it('should initialize Octokit with the correct token', () => {
    expect(Octokit).toHaveBeenCalledWith({ auth: 'test-token' });
  });

  describe('saveMarkdown', () => {
    const summaryResult = {
      title: '테스트 제목',
      oneline: 'NestJS는 모듈 기반 아키텍처로 대규모 애플리케이션 개발에 적합하다.',
      description: 'test-slug',
      category: 'Tech',
      tags: ['nestjs', 'typescript', 'testing'],
      keywords: ['NestJS', '타입스크립트', '테스트'],
      concepts: {
        upper: ['백엔드 프레임워크'],
        lower: ['의존성 주입', '모듈 시스템'],
        related: ['Express', 'Spring Boot'],
        prerequisite: ['Node.js 기초'],
        followup: ['마이크로서비스 아키텍처'],
      },
      quotes: [
        { text: 'NestJS provides a modular architecture out of the box.', context: 'NestJS의 핵심 설계 철학을 선언하는 문장이다.' },
      ],
      insights: ['**모듈 아키텍처의 강점**: NestJS는 모듈 기반 아키텍처로 대규모 애플리케이션에 적합하다.'],
      decoded: 'NestJS는 기능별로 코드를 나눠 관리하는 구조를 갖고 있다. 마치 레고 블록처럼 각 기능을 독립적으로 조립하고 교체할 수 있어 대규모 프로젝트에서도 관리가 용이하다.',
      summary: '## 요약\n\nNestJS는 모듈 기반 아키텍처를 채택하여 대규모 애플리케이션 개발에 적합한 프레임워크다. 의존성 주입과 모듈 시스템을 통해 코드의 재사용성과 테스트 용이성을 동시에 확보할 수 있다.',
    };
    const sourceUrl = 'https://example.com/article';

    it('should save markdown to GitHub and return htmlUrl and filePath', async () => {
      const { htmlUrl, filePath } = await service.saveMarkdown(summaryResult, sourceUrl);

      expect(htmlUrl).toBe(
        'https://github.com/owner/repo/blob/main/98-summaries/2026-02-10-test-slug.md',
      );
      expect(filePath).toMatch(/^98-summaries\/\d{4}-\d{2}-\d{2}-test-slug\.md$/);

      expect(
        mockOctokit.repos.createOrUpdateFileContents,
      ).toHaveBeenCalledTimes(1);

      const call =
        mockOctokit.repos.createOrUpdateFileContents.mock.calls[0][0];
      expect(call.owner).toBe('owner');
      expect(call.repo).toBe('repo');
      expect(call.path).toMatch(
        /^98-summaries\/\d{4}-\d{2}-\d{2}-test-slug\.md$/,
      );
      expect(call.message).toBe('docs: add summary - 테스트 제목');
      expect(call.content).toBeDefined();
    });

    it('should generate valid markdown with frontmatter', async () => {
      await service.saveMarkdown(summaryResult, sourceUrl);

      const call =
        mockOctokit.repos.createOrUpdateFileContents.mock.calls[0][0];
      const decoded = Buffer.from(call.content, 'base64').toString('utf-8');

      expect(decoded).toContain('---');
      expect(decoded).toContain('title: "테스트 제목"');
      expect(decoded).toContain('category: Tech');
      expect(decoded).toContain('tags: [nestjs, typescript, testing]');
      expect(decoded).toContain(`source: "${sourceUrl}"`);
      expect(decoded).toContain('## 한줄 요약');
      expect(decoded).toContain('## 핵심 인사이트');
      expect(decoded).toContain('## 쉬운 해석');
      expect(decoded).toContain('## 주요 원문');
      expect(decoded).toContain('## 지식 맵');
      expect(decoded).toContain('**선행**');
      expect(decoded).toContain('**후속**');
      expect(decoded).toContain('> Auto-generated by Summary Bot on');
    });

    it('should return empty string when html_url is not available', async () => {
      mockOctokit.repos.createOrUpdateFileContents.mockResolvedValueOnce({
        data: { content: null },
      });

      const { htmlUrl } = await service.saveMarkdown(summaryResult, sourceUrl);
      expect(htmlUrl).toBe('');
    });
  });

  describe('deleteMarkdown', () => {
    const filePath = '98-summaries/2026-02-10-test-slug.md';

    it('should fetch SHA and delete the file', async () => {
      await service.deleteMarkdown(filePath);

      expect(mockOctokit.repos.getContent).toHaveBeenCalledWith({
        owner: 'owner',
        repo: 'repo',
        path: filePath,
      });

      expect(mockOctokit.repos.deleteFile).toHaveBeenCalledWith({
        owner: 'owner',
        repo: 'repo',
        path: filePath,
        message: `docs: remove summary - ${filePath}`,
        sha: 'abc123sha',
      });
    });

    it('should propagate error when getContent fails', async () => {
      mockOctokit.repos.getContent.mockRejectedValueOnce(
        new Error('Not Found'),
      );

      await expect(service.deleteMarkdown(filePath)).rejects.toThrow(
        'Not Found',
      );
    });
  });
});
