import { Test, TestingModule } from '@nestjs/testing';
import { ConfigService } from '@nestjs/config';
import { GithubService } from './github.service';

jest.mock('@octokit/rest', () => ({
  Octokit: jest.fn().mockImplementation(() => ({
    repos: {
      createOrUpdateFileContents: jest.fn().mockResolvedValue({
        data: {
          content: {
            html_url: 'https://github.com/owner/repo/blob/main/98-summaries/2026-02-10-test-slug.md',
          },
        },
      }),
    },
  })),
}));

import { Octokit } from '@octokit/rest';

describe('GithubService', () => {
  let service: GithubService;
  let mockOctokit: jest.Mocked<any>;

  const mockConfigService = {
    get: jest.fn((key: string) => {
      const config = {
        'github.token': 'test-token',
        'github.repo': 'owner/repo',
        'github.summaryDir': '98-summaries',
      };
      return config[key];
    }),
  };

  beforeEach(async () => {
    jest.clearAllMocks();

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        GithubService,
        { provide: ConfigService, useValue: mockConfigService },
      ],
    }).compile();

    service = module.get<GithubService>(GithubService);
    mockOctokit = (Octokit as jest.MockedClass<typeof Octokit>).mock.results[
      (Octokit as jest.MockedClass<typeof Octokit>).mock.results.length - 1
    ].value;
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  it('should initialize Octokit with the correct token', () => {
    expect(Octokit).toHaveBeenCalledWith({ auth: 'test-token' });
  });

  describe('saveMarkdown', () => {
    const summaryResult = {
      title: '테스트 제목',
      description: 'test-slug',
      category: 'Tech',
      tags: ['nestjs', 'typescript', 'testing'],
      keywords: ['NestJS', '타입스크립트', '테스트'],
      concepts: {
        upper: ['백엔드 프레임워크'],
        lower: ['의존성 주입', '모듈 시스템'],
        related: ['Express', 'Spring Boot'],
      },
      insights: ['NestJS는 모듈 기반 아키텍처로 대규모 애플리케이션에 적합하다.'],
      summary: '## 요약\n\n테스트 요약 내용입니다.',
    };
    const sourceUrl = 'https://example.com/article';

    it('should save markdown to GitHub and return html_url', async () => {
      const url = await service.saveMarkdown(summaryResult, sourceUrl);

      expect(url).toBe(
        'https://github.com/owner/repo/blob/main/98-summaries/2026-02-10-test-slug.md',
      );

      expect(
        mockOctokit.repos.createOrUpdateFileContents,
      ).toHaveBeenCalledTimes(1);

      const call =
        mockOctokit.repos.createOrUpdateFileContents.mock.calls[0][0];
      expect(call.owner).toBe('owner');
      expect(call.repo).toBe('repo');
      expect(call.path).toMatch(
        /^98-summaries\/\d{4}-\d{2}-\d{2}-test-slug\.md$/,
      );
      expect(call.message).toBe('docs: add summary - 테스트 제목');
      expect(call.content).toBeDefined();
    });

    it('should generate valid markdown with frontmatter', async () => {
      await service.saveMarkdown(summaryResult, sourceUrl);

      const call =
        mockOctokit.repos.createOrUpdateFileContents.mock.calls[0][0];
      const decoded = Buffer.from(call.content, 'base64').toString('utf-8');

      expect(decoded).toContain('---');
      expect(decoded).toContain('title: "테스트 제목"');
      expect(decoded).toContain('category: Tech');
      expect(decoded).toContain('tags: [nestjs, typescript, testing]');
      expect(decoded).toContain(`source: "${sourceUrl}"`);
      expect(decoded).toContain('## 요약');
      expect(decoded).toContain('테스트 요약 내용입니다.');
      expect(decoded).toContain('> Auto-generated by Summary Bot on');
    });

    it('should return empty string when html_url is not available', async () => {
      mockOctokit.repos.createOrUpdateFileContents.mockResolvedValueOnce({
        data: { content: null },
      });

      const url = await service.saveMarkdown(summaryResult, sourceUrl);
      expect(url).toBe('');
    });
  });
});
